// <auto-generated />
namespace TourismWebProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class NewChanges13 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewChanges13));
        
        string IMigrationMetadata.Id
        {
            get { return "201902232010127_NewChanges13"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
