// <auto-generated />
namespace TourismWebProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Newchanges36 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Newchanges36));
        
        string IMigrationMetadata.Id
        {
            get { return "201903041550289_New changes36"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
