// <auto-generated />
namespace TourismWebProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Newchanges34 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Newchanges34));
        
        string IMigrationMetadata.Id
        {
            get { return "201903041251577_New changes34"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
